### ISSUE TITLE
Icon not showing for the plugin in the catalog

### ISSUE THREAD

**Issue by Rasbats** [Hakansv/AIS_VD_pi#4]
As the heading says. Have a look at ShipDriver to see how the icon is added to the catalog list of installed plugins.

**Comment by Hakansv** [comment]
Are we talking about the puzzle icon, see pict?
If so I haven't done any but are using the default_pi.xpm. In my mind that was good enough for this? :)
Thoughts?
Håkan

![bild](https://user-images.githubusercontent.com/7202854/145718821-ff404f89-1537-49ab-a2fe-5341566713c8.png)

**Comment by Rasbats** [comment]
Yes ... the puzzle icon should (maybe could) be an image you want to identify the plugin. I know you are adding to options/ship tabs. Maybe not needed. I was just was not expecting it. 

You are right ... oeSENC does a similar thing. Maybe best to keep it simple and ignore this.

**Comment by leamas** [comment]
> You are right ... oeSENC does a similar thing. Maybe best to keep it simple and ignore this.

oeSENC is about to be retired shortly, to be replaced with the new o-charts plugin. While working with that plugin we all agreed that (ab)using the jigsaw icon is problematic, partly just because of the optics, partly because in most cases the jigsaw icon indicates a bug. 

So, if it is not too much work I think using a "real" icon is an advantage.

**Comment by Hakansv** [comment]
Without having looked into it at all there seems to be some general icon trouble. I may await that "storm" to calm.

re: "indicates a bug"
So the Plugins is a bug as such?? (Sorry - nasty joke )

![bild](https://user-images.githubusercontent.com/7202854/146158720-b5f6ff71-07cb-4c64-9d7a-52cfe230073b.png)
